# Shared constants for the Snake game
CELL_SIZE = 20
MOVE_DISTANCE = CELL_SIZE
STARTING_POSITIONS = [(0, 0), (-CELL_SIZE, 0), (-CELL_SIZE * 2, 0), (-CELL_SIZE * 3, 0), (-CELL_SIZE * 4, 0)]
SNAKE_DEFAULT_SPEED = 200 # lower is faster

#: x axys; 
GRID_WIDTH_FROM_CENTER = 15
GRID_WIDTH = GRID_WIDTH_FROM_CENTER * 2 + 1 # MUST BE AN ODD NUMBER
SCREEN_WIDTH = CELL_SIZE * GRID_WIDTH

#: y axys; 
GRID_LENGTH_FROM_CENTER = 15
GRID_LENGTH = GRID_LENGTH_FROM_CENTER * 2 + 1 # MUST BE AN ODD NUMBER
SCREEN_LENGTH = CELL_SIZE * GRID_LENGTH

WALLS_MARGIN_OFFSET = 50