# Shared constants for the Snake game
CELL_SIZE = 20
MOVE_DISTANCE = CELL_SIZE
STARTING_POSITIONS = [(0, 0), (-CELL_SIZE, 0), (-CELL_SIZE * 2, 0), (-CELL_SIZE * 3, 0), (-CELL_SIZE * 4, 0)]
SNAKE_DEFAULT_SPEED = 200 # lower is faster

#: x axys; MUST BE AN ODD NUMBER
GRID_WIDTH = 33
SCREEN_WIDTH = CELL_SIZE * GRID_WIDTH

#: y axys; MUST BE AN ODD NUMBER
GRID_LENGTH = 33
SCREEN_LENGTH = CELL_SIZE * GRID_LENGTH

WALLS_MARGIN_OFFSET = 50